// App
export const ACTIVE_CAPTURE = 'ACTIVE_CAPTURE'
export const ACTIVE_FLOORPLAN = 'ACTIVE_FLOORPLAN'
export const ACTIVE_HOTSPOT = 'ACTIVE_HOTSPOT'
export const ACTIVE_ROOM = 'ACTIVE_ROOM'
export const ACTIVE_ROOMS = 'ACTIVE_ROOMS'
export const ACTIVE_ROTATION = 'ACTIVE_ROTATION'
export const LOADING = 'LOADING'
export const RESET_APP = 'RESET_APP'
export const SETTING_AUTO_SAVE = 'SETTING_AUTO_SAVE'
export const SETTING_INVERT_CONTROLS = 'SETTING_INVERT_CONTROLS'

// Camera
export const CAMERA_INFO = 'CAMERA_INFO'
export const SESSION = 'SESSION'

// Captures
export const ADD_CAPTURE = 'ADD_CAPTURE'
export const DELETE_CAPTURE = 'DELETE_CAPTURE'
export const UPDATE_CAPTURE = 'UPDATE_CAPTURE'

// FloorPlan
export const ADD_FLOORPLAN = 'ADD_FLOORPLAN'
export const DELETE_FLOORPLAN = 'DELETE_FLOORPLAN'
export const UPDATE_FLOORPLAN = 'UPDATE_FLOORPLAN'

// Hotspots
export const ADD_HOTSPOT = 'ADD_HOTSPOT'
export const DELETE_HOTSPOT = 'DELETE_HOTSPOT'
export const UPDATE_HOTSPOT = 'UPDATE_HOTSPOT'

// Notification
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'

// Properties
export const ADD_CLOUD_PROPERTIES = 'ADD_CLOUD_PROPERTIES'
export const ADD_LOCAL_PROPERTY = 'ADD_LOCAL_PROPERTY'
export const CLOUD_PROPERTIES = 'CLOUD_PROPERTIES'
export const LOCAL_PROPERTIES = 'LOCAL_PROPERTIES'
export const DELETE_CLOUD_PROPERTY = 'DELETE_CLOUD_PROPERTY'
export const DELETE_LOCAL_PROPERTY = 'DELETE_LOCAL_PROPERTY'
export const PROPERTY_XFER_COMPLETE = 'PROPERTY_XFER_COMPLETE'
export const PROPERTY_XFER_START = 'PROPERTY_XFER_START'

// Rooms
export const ADD_ROOM = 'ROOM'
export const DELETE_ROOM = 'DELETE_ROOM'
export const UPDATE_ROOM = 'UPDATE_ROOM'

// Screenshots
export const ADD_SCREENSHOT = 'ADD_SCREENSHOT'
export const DELETE_SCREENSHOT = 'DELETE_SCREENSHOT'
export const UPDATE_SCREENSHOT = 'UPDATE_SCREENSHOT'
