// App
export const ACTIVE_CAPTURE = 'ACTIVE_CAPTURE'
export const ACTIVE_FLOORPLAN = 'ACTIVE_FLOORPLAN'
export const ACTIVE_HOTSPOT = 'ACTIVE_HOTSPOT'
export const ACTIVE_ROOM = 'ACTIVE_ROOM'
export const ACTIVE_ROOMS = 'ACTIVE_ROOMS'
export const LOADING = 'LOADING'
export const RESET_APP = 'RESET_APP'
export const ROTATION = 'ROTATION'
export const SETTING_AUTO_SAVE = 'SETTING_AUTO_SAVE'
export const SETTING_INVERT_CONTROLS = 'SETTING_INVERT_CONTROLS'

// Camera
export const CAMERA_INFO = 'CAMERA_INFO'
export const SESSION = 'SESSION'

// Captures
export const CAPTURE = 'CAPTURE'
export const CAPTURE_NAME = 'CAPTURE_NAME'
export const CAPTURE_NOTE = 'CAPTURE_NOTE'
export const DELETE_CAPTURE = 'DELETE_CAPTURE'

// FloorPlan
export const ADD_FLOORPLAN = 'ADD_FLOORPLAN'
export const DELETE_FLOORPLAN = 'DELETE_FLOORPLAN'
export const SET_FLOORPLANS = 'SET_FLOORPLANS'
export const UPDATE_FLOORPLAN = 'UPDATE_FLOORPLAN'
export const UPDATE_FLOORPLAN_ADDROOM = 'UPDATE_FLOORPLAN_ADDROOM'
export const UPDATE_FLOORPLAN_DELETEROOM = 'UPDATE_FLOORPLAN_DELETEROOM'
export const UPDATE_FLOORPLAN_UPDATEROOM = 'UPDATE_FLOORPLAN_UPDATEROOM'

// Hotspots
export const ADD_BLUR = 'ADD_BLUR'
export const DELETE_HOTSPOT = 'DELETE_HOTSPOT'
export const EDIT_BLUR = 'EDIT_BLUR'
export const HOTSPOT = 'HOTSPOT'

// Notification
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'
export const NOTIFICATION = 'NOTIFICATION'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'

// Properties
export const ADD_CLOUD_PROPERTIES = 'ADD_CLOUD_PROPERTIES'
export const CLOUD_PROPERTIES = 'CLOUD_PROPERTIES'
export const DELETE_LOCAL_PROPERTY = 'DELETE_LOCAL_PROPERTY'
export const LOCAL_PROPERTIES = 'LOCAL_PROPERTIES'
export const NEW_LOCAL_PROPERTY = 'NEW_LOCAL_PROPERTY'
export const PROPERTY_XFER_COMPLETE = 'PROPERTY_XFER_COMPLETE'
export const PROPERTY_XFER_START = 'PROPERTY_XFER_START'
export const REMOVE_CLOUD_PROPERTY = 'REMOVE_CLOUD_PROPERTY'

// Rooms
export const DELETE_ROOM = 'DELETE_ROOM'
export const ROOM = 'ROOM'
export const SET_ROOMS = 'SET_ROOMS'
export const UPDATE_ROOM = 'UPDATE_ROOM'

// Screenshots
export const DELETE_SCREENSHOT = 'DELETE_SCREENSHOT'
export const SCREENSHOT = 'SCREENSHOT'
